logo:
  #nav_mobile: images/logo-apollo-space-left.svg
  #subbrand: images/logo-apollo-subbrands-developers-space.svg
  title: Nova
  subtitle: Docs
  url: http://nova-docs.telescopeapp.org/
#favicon: images/favicon.png

nav_links:
  'GitHub':
    url: https://github.com/telescopejs/telescope
  'Slack':
    url: http://slack.telescopeapp.org
